/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.coreteka;

import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {

    public static void main(String[] args) {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("spring-config-servlet.xml");
        context.getBean("myDataSource");
    }
}
